apiVersion: v1
kind: Service
metadata:
  name: ga-chp-service
  labels:
    run: ga-chp
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 6868
  selector:
    run: ga-chp

